### ISSUE TITLE
Non node.js usage

### ISSUE THREAD

**Issue by paul-hammant** [lifenautjoe/droppable#10]
The tech is tied to NPM it seems from the documentation. 

Not all people that would use this would do so via NPM. Some devs would want to use this from a Django/Flask/SpringBoot/Razor.NET backend without a NPM-ish build/deploy toolchain being involved. Thus they'd like to read how to integrate it via a script tag. See how Vue.js talks about you install choices - https://vuejs.org/v2/guide/installation.html

**Comment by lifenautjoe** [comment]
Very good point. I will provide alternative install choices.

Thank you!

**Comment by lifenautjoe** [comment]
Hey @paul-hammant , the distribution files are now tracked by git, have added the files as release binaries and have added some documentation on this [here](https://github.com/lifenautjoe/droppable#scripts). 

Does this help? For the CDN option, need to meet a usage criteria at CDNjs.

**Comment by paul-hammant** [comment]
Very good. I'm thinking you're some words though: 
![image](https://user-images.githubusercontent.com/82182/38473017-9ed2ca66-3b56-11e8-9fa9-3b908d5d8e15.png)

**Comment by lifenautjoe** [comment]
@paul-hammant whoops! Totally missed it. Fixed and thank you!
