### ISSUE TITLE
Cannot use 'new' with an expression whose type lacks a call or construct signature

### ISSUE THREAD

**Issue by famu1hundred** [lifenautjoe/droppable#24]
`import * as Droppable from 'droppable';`
`this.droppable = new Droppable({`
     ` element: document.querySelector('#droppable-area'),`
      `acceptsMultipleFiles: false`
`    });`

This produces the following error: 
Cannot use 'new' with an expression whose type lacks a call or construct signature.

**Comment by lifenautjoe** [comment]
Hey there @famu1hundred ,

The library has a default export.

Try `import Droppable from 'droppable';` please.

**Comment by famu1hundred** [comment]
Actually I got it to work using the following
`import * as Droppable from 'droppable';`
`this.droppable = new Droppable.default({`
     ` element: document.getElementById('droppable-area'),`
     ` acceptsMultipleFiles: false`
`    });`

**Comment by famu1hundred** [comment]
I also tried your import and it worked as well!
